seed: 1234

dataset:
  mode: paired
  pair_by_order: false

  lq:
    root: "data/train/inputs"
    decoder:
      type: image
    pipeline: []

  gt:
    root: "data/train/targets"
    decoder:
      type: image
    pipeline: []

patching:
  mode: grid
  size: 256
  stride: 256

packing:
  output_root: "data/train_paired_lmdb"
  show_progress: true
  outputs:
    lq:
      enabled: true
      pipeline:
        - name: "store_rgb_png"
          params:
            png_compress_level: 3
        - name: "write_lmdb"
          params:
            lmdb_name: "lq.lmdb"
            map_size_gb: 0.25
            write_batch_size: 512
            compact: true
    gt:
      enabled: true
      pipeline:
        - name: "store_rgb_png"
          params:
            png_compress_level: 3
        - name: "write_lmdb"
          params:
            lmdb_name: "gt.lmdb"
            map_size_gb: 0.25
            write_batch_size: 512
            compact: true
